dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# Install dependencies
before_install:
  - python --version
install:
  - pip install -r requirements.txt
# Execute the tests and the linter
script:
  - pytest --cov=things_organizer
  - pylint -f parseable --rcfile=.pylintrc things_organizer
  - echo "Done"
