dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# Install dependencies
install:
  - pip install -r requirements.txt
# Execute the tests and the linter
script:
  - pytest && pylint --errors-only
  - echo "Done"
